# Generated by Django 4.1.7 on 2023-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="courseApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_and_Last_Name", models.CharField(blank=True, max_length=100)),
                (
                    "courses",
                    models.CharField(
                        choices=[
                            (
                                "Monday 6-6:50, CSCI 1101.01.01",
                                "Discussion Times: Monday 6-6:50",
                            ),
                            (
                                "Tuesday 6-6:50, CSCI 1101.01.02",
                                "Discussion Times: Tuesday 6-6:50",
                            ),
                            (
                                "Wednesday 2-2:50, CSCI 1101.01.03",
                                "Discussion Times: Wednesday 2-2:50",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
