# Generated by Django 4.1.5 on 2023-03-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discussion_Time_1', models.CharField(choices=[('Monday 6-6:50, CSCI 1101.01.01', 'Monday 6-6:50'), ('Tuesday 6-6:50, CSCI 1101.01.02', 'Tuesday 6-6:50'), ('Wednesday 2-2:50, CSCI 1101.01.03', 'Wednesday 2-2:50')], max_length=100)),
                ('Discussion_Time_2', models.CharField(choices=[('Monday 6-6:50, CSCI 1101.01.01', 'Monday 6-6:50'), ('Tuesday 6-6:50, CSCI 1101.01.02', 'Tuesday 6-6:50'), ('Wednesday 2-2:50, CSCI 1101.01.03', 'Wednesday 2-2:50')], max_length=100)),
                ('First_and_Last_Name', models.CharField(blank=True, max_length=100)),
                ('Resume', models.FileField(upload_to='resumes/')),
                ('Cover_Letter', models.FileField(upload_to='cover_letters/')),
                ('Reference_Letter', models.FileField(upload_to='reference_letters/')),
            ],
        ),
    ]
