# Generated by Django 4.1.7 on 2023-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='Discussion_Time_1',
            field=models.CharField(choices=[('Monday 6-6:50', 'Monday 6-6:50'), ('Tuesday 6-6:50', 'Tuesday 6-6:50'), ('Wednesday 2-2:50', 'Wednesday 2-2:50')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='Discussion_Time_2',
            field=models.CharField(choices=[('Monday 6-6:50', 'Monday 6-6:50'), ('Tuesday 6-6:50', 'Tuesday 6-6:50'), ('Wednesday 2-2:50', 'Wednesday 2-2:50')], max_length=100),
        ),
    ]
