# Generated by Django 4.1.7 on 2023-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="courseApplicationOnlyResume",
        ),
        migrations.RemoveField(
            model_name="courseapplicationallrequired",
            name="Cover_Letter",
        ),
        migrations.RemoveField(
            model_name="courseapplicationallrequired",
            name="Reference_Letter",
        ),
        migrations.AddField(
            model_name="courseapplicationallrequired",
            name="Anything_you_want_to_add",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="courseapplicationallrequired",
            name="Username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
