# Generated by Django 4.1.5 on 2023-04-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_courseapplication_discussion_time_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='Cover_Letter',
            field=models.FileField(upload_to='course_app/cover_letters/'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='Reference_Letter',
            field=models.FileField(upload_to='course_app/reference_letters/'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='Resume',
            field=models.FileField(upload_to='course_app/resumes/'),
        ),
    ]
