# Generated by Django 4.1.5 on 2023-04-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_courseapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='Course_Name',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
