# Generated by Django 4.1.5 on 2023-04-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_courseapplication_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseapplication',
            name='Course_Name',
        ),
    ]
