# Generated by Django 4.1.5 on 2023-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_remove_courseapplication_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='Course_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
