# Generated by Django 4.1.5 on 2023-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_alter_courseapplication_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='Course_Name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
