# Generated by Django 4.1.5 on 2023-04-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_alter_courseapplication_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='Course_Section',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
