# Generated by Django 4.1.5 on 2023-04-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_courseapplication_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='Cover_Letter',
            field=models.FileField(blank=True, upload_to='course_app/cover_letters/'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='First_and_Last_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='Reference_Letter',
            field=models.FileField(blank=True, upload_to='course_app/reference_letters/'),
        ),
    ]
