# Generated by Django 4.1.7 on 2023-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0012_courseapplicationallrequired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseapplicationallrequired",
            name="Username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="courseapplicationonlyresume",
            name="Username",
            field=models.CharField(default="", max_length=100),
        ),
    ]
